game/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/<str:lobby_name>/', views.register, name='register'),
    path('game/<str:lobby_name>/<str:user_name>/', views.lobby, name='lobby'),
]

mafia_main/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    path('', include('game.urls')),
    path('admin/', admin.site.urls),
]

game/models.py
from django.db import models


class RoomStatus(models.IntegerChoices):
    """Статус игры"""
    PRE_GAME = 1
    IN_GAME = 2
    END_GAME = 3


class RoomTimeStatus(models.IntegerChoices):
    """Город засыпает, просыпаеться мафия"""
    DAY = 1
    NIGHT = 2


class UserStatus(models.IntegerChoices):
    """Статус игрока"""
    LIVE = 1
    DEAD = 2


class UserType(models.IntegerChoices):
    """Тип игрока"""
    LEADER = 1
    CITIZEN = 2
    MAFIA = 3


class GameRoom(models.Model):
    """Модель игровой комнаты"""
    room_name = models.CharField('Название лобби', max_length=128)
    room_status = models.IntegerField('Статус лобби', default=1, choices=RoomStatus.choices)
    game_time = models.IntegerField('Время суток в игре', default=1, choices=RoomTimeStatus.choices)
    chat = models.TextField('Чат', blank=True, null=True)
    mafia_chat = models.TextField('Чат мафии', blank=True, null=True)

    def __str__(self):
        return f'{self.room_name}'


class GameUser(models.Model):
    """Модель игрока"""
    user_name = models.CharField('Имя игрока', max_length=128)
    user_status = models.IntegerField('Статус пользователя', default=1, choices=UserStatus.choices)
    user_type = models.IntegerField('Тип пользователя', default=1, choices=UserType.choices)
    room = models.ForeignKey(GameRoom, models.CASCADE, related_name='users')
    channel_name = models.CharField('Имя приватного канала', max_length=256, null=True, blank=True)

    def __str__(self):
        return f'{self.user_name}'

game/views.py
from django.shortcuts import render, redirect

from game.models import GameRoom, GameUser


def index(request):
    """Главная страница. Выбор комнаты"""
    return render(request, 'game/index.html')


def register(request, lobby_name):
    """Страница с регистрации. Выбор имени"""
    if request.GET.get('leading'):
        GameRoom.objects.create(room_name=lobby_name)
        return render(request, 'game/register.html', {'lobby_name': lobby_name})
    if not GameRoom.objects.filter(room_name=lobby_name).exists():
        request.session['error'] = 'Комната не найдена'
        return redirect('index')
    return render(request, 'game/register.html', {'lobby_name': lobby_name})


def create_user(leader, room, user_name):
    """Создать пользователя"""
    if GameUser.objects.filter(user_name=user_name, room=room).exists():
        return GameUser.objects.get(user_name=user_name, room=room)
    if leader == 'true':
        return GameUser.objects.create(user_name=user_name, room=room)
    else:
        return GameUser.objects.create(user_name=user_name, room=room, user_type=2)


def register_user(room, user_name):
    """Найти пользователя"""
    if GameUser.objects.filter(user_name=user_name, room=room).exists():
        return GameUser.objects.get(user_name=user_name, room=room)
    return False


def lobby(request, lobby_name, user_name):
    """Команаты игры"""
    leader = request.GET.get('leading')
    try:
        room = GameRoom.objects.get(room_name=lobby_name)
        user = False
        if room.room_status == 1:
            if room.users.count() >= 9 and not GameUser.objects.filter(user_name=user_name, room=room).exists():
                request.session['error'] = 'Игра уже началась'
                return redirect('index')
            user = create_user(leader, room, user_name)
        elif room.room_status == 2:
            user = register_user(room, user_name)
        if not user:
            request.session['name_error'] = 'Игра уже началась'
            return redirect('register', lobby_name=lobby_name)
        return render(request, 'game/lobby.html', {'lobby': room, 'user': user})
    except GameRoom.DoesNotExist:
        request.session['error'] = 'Комната не найдена'
        return redirect('index')

game/templates/game/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Выбор лобби</title>
</head>
<body>
    <h1 style="color: red">{{ request.session.error }}</h1>
    Введите название лобби:<br><br>
    <input id="room-name-input" type="text" size="100"><br><br>
    <input id="room-name-submit" type="button" value="Войти"><br><br><br><br>
    Или создайте собственное лобби и станьте ведущим:<br><br>
    <input id="room-name-create" type="text" size="100"><br><br>
    <input id="room-name-create-submit" type="button" value="Создать"><br><br>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            const roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/register/' + roomName + '/';
        };
        document.querySelector('#room-name-create').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-create-submit').click();
            }
        };

        document.querySelector('#room-name-create-submit').onclick = function(e) {
            const roomName = document.querySelector('#room-name-create').value;
            window.location = '/register/' + roomName + '/?leading=' + encodeURIComponent(true);
        };
    </script>
</body>
</html>

game/templates/game/lobby.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Лобби игры</title>
</head>
<body>
<h2>Название лобби: {{ lobby.room_name }}... Ваше имя: {{ user.user_name }}... Ваша
    роль: {{ user.get_user_type_display }}</h2>
<div id="user-list">Список игроков:
    {% for player in lobby.users.all %}
        {% if player.user_type != 1 %}
            <span id="{{ player.user_name }}"
                    {% if player.user_status == 2 %}
                  style="text-decoration: line-through"
                    {% endif %}>
                | {{ player.user_name }} |,
            </span>
        {% endif %}
    {% endfor %}
</div>

<div id="leader_panel" {% if not user.user_type == 1 %}
     hidden
{% endif %}
>
    <p>Консоль ведущего:</p>

    <input id="start-game-button" type="button" value="Начать игру"
            {% if not lobby.room_status == 1 or not lobby.users.count == 9 %}
           hidden
            {% endif %}
    >

    <input id="kill-input" type="text" size="80">
    <input id="kill-submit" type="button" value="Убить">

    <input id="day_start" type="button" value="Начать день"
            {% if lobby.game_time == 1 %}
           hidden
            {% endif %}
    >

    <input id="night_start" type="button" value="Начать ночь"
            {% if lobby.game_time == 2 %}
           hidden
            {% endif %}
    >
</div>
<div id="game-lobby">
    <p>Общий чат</p>
    <textarea id="chat-log" cols="70" rows="15">{% if lobby.chat %}{{ lobby.chat }}{% endif %}</textarea><br>
    <input id="chat-message-input" type="text" size="80"><br>
    <input id="chat-message-submit" type="button" value="Отправить"
            {% if user.user_status == 2 %}
           disabled
            {% endif %}
            {% if lobby.game_time == 2 %}
           disabled
            {% endif %}
    >
</div>
<div id="mafia-chat" {% if user.user_type == 2 %}style="display: none"{% endif %}>
    <p>Чат мафии</p>
    <textarea id="mafia-chat-log" cols="70" rows="15">{% if lobby.mafia_chat %}
        {{ lobby.mafia_chat }}{% endif %}</textarea><br>
    <input id="mafia-message-input" type="text" size="80"><br>
    <input id="mafia-message-submit" type="button" value="Отправить"
            {% if user.user_status == 2 %}
           disabled
            {% endif %}
            {% if lobby.game_time == 1 %}
           disabled
            {% endif %}
    >
</div>
{{ lobby.room_name|json_script:"lobby-name" }}
{{ lobby.game_time|json_script:"lobby-time" }}
{{ user.user_name|json_script:"user" }}
<script>
    const lobbyTime = JSON.parse(document.getElementById('lobby-time').textContent);
    const lobbyName = JSON.parse(document.getElementById('lobby-name').textContent);
    const userName = JSON.parse(document.getElementById('user').textContent);

    if (lobbyTime === 1) {
        document.body.style.backgroundColor = 'white'
    } else {
        document.body.style.backgroundColor = 'darkgrey'
    }

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/lobby/'
        + lobbyName
        + '/'
        + userName
        + '/'
    );

    chatSocket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        if (data.message.type === 'chat_message') {
            document.querySelector('#chat-log').value += (data.message.message + '\n');
        } else if (data.message.type === 'chat_mafia') {
            document.querySelector('#mafia-chat-log').value += (data.message.message + '\n');
        } else if (data.message.type === 'reload') {
            location.reload()
        }
    };

    chatSocket.onclose = function (e) {
        console.error('Проблема связи с сервером');
    };

    document.querySelector('#chat-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#mafia-message-input').onkeyup = function (e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#mafia-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function (e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'type': 'chat_message',
            'message': message
        }));
        messageInputDom.value = '';
    };

    document.querySelector('#mafia-message-submit').onclick = function (e) {
        const messageInputDom = document.querySelector('#mafia-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'type': 'chat_mafia',
            'message': message
        }));
        messageInputDom.value = '';
    };

    document.querySelector('#kill-submit').onclick = function (e) {
        const messageInputDom = document.querySelector('#kill-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'type': 'kill_user',
            'message': message
        }));
        messageInputDom.value = '';
    };

    document.querySelector('#start-game-button').onclick = function (e) {
        chatSocket.send(JSON.stringify({
            'type': 'start_game',
            'message': 'start_game'
        }));
    };

    document.querySelector(`#day_start`).onclick = function (e) {
        chatSocket.send(JSON.stringify({
            'type': 'day_start',
            'message': 'day_start'
        }));
    };

    document.querySelector('#night_start').onclick = function (e) {
        chatSocket.send(JSON.stringify({
            'type': 'night_start',
            'message': 'night_start'
        }));
    };
</script>
</body>
</html>

game/templates/game/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div id="register">
    <p>Выбирите имя: </p>
    <input id="register-input" type="text" size="100"><br>
    <input id="register-submit" type="button" value="Выбрать"><br>
</div>
{{ lobby_name|json_script:"lobby-name" }}
<script>
    document.querySelector('#register-input').focus();
    document.querySelector('#register-input').onkeyup = function (e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#register-submit').click();
        }
    };

    document.querySelector('#register-submit').onclick = function (e) {
        const nameInputDom = document.querySelector('#register-input');
        const name = nameInputDom.value;
        const urlParams = new URLSearchParams(window.location.search);
        const roleParam = urlParams.get('leading');
        console.log(roleParam);
        const leader = !!roleParam;
        const lobbyName = JSON.parse(document.getElementById('lobby-name').textContent);
        window.location = '/game/' + lobbyName + '/' + name + '/?leading=' + encodeURIComponent(leader);
    };
</script>
</body>
</html>